### ISSUE TITLE
[BUG]  [UI]  包无忧管理系统  BUG-0001  查询快件页面和监控派件页面的标题重复

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#1]
1、点击进入包无忧管理系统；
2、分别点击“查询快件”按钮和“监控派件”按钮并进入相应页面，显示标题均为：包裹单状态查询；
3、期望结果：查询快件页面的标题显示不变，监控派件页面的标题为：包无忧快递查询列表。

**Comment by smileyWay** [comment]
已修改。

**Comment by 1182311224** [comment]
问题已修复。
