### ISSUE TITLE
[BUG]  [功能]  包无忧管理系统  BUG-0002  语音通知页面两个不同店铺显示的快件内容是一样的

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#2]
1、点击进入包无忧管理系统；
2、点击“通知取货”按钮；
3、选择店铺：钢五区，点击“查询”按钮，会显示钢五区到目前为止尚未出库需语音通知的记录，如图1部分截图；
4、重新选择店铺：莲花逸都，点击“查询”按钮，此时显示的快件记录内容和钢五区店铺记录内容一致，如图2部分截图；
5、期望结果：两个店铺能正确显示各自的快件信息。
![1](https://cloud.githubusercontent.com/assets/20570761/17844846/2b309bde-6870-11e6-90aa-df6fb503531e.png)
![2](https://cloud.githubusercontent.com/assets/20570761/17844849/2f56b46e-6870-11e6-8e73-cded92a9978f.png)

**Comment by smileyWay** [comment]
已修复。

**Comment by 1182311224** [comment]
问题已修复。
