### ISSUE TITLE
[BUG]  [功能]  包无忧管理系统  BUG-0003  通知取货页面，当取消某一条记录勾选时，全选框未取消选中

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#3]
1、点击进入包无忧管理系统；
2、点击进入通知取货页面；
3、选中8月22日快件记录的全选框，此时8月22日当天未出库的记录全部选中；
4、取消8月22日某一条记录的勾选，此时8月22日快件记录的全选框仍然是选中状态；
5、期望结果：当取消某一条记录的勾选时，全选框应取消选中。

**Comment by smileyWay** [comment]
暂时不修改，等后期再修复。
