### ISSUE TITLE
［BUG]  [UI]  包无忧管理系统  BUG-0004 在查询快件页面进行快件的搜索时，无加载提示和未查询到记录的提示

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#4]
1、点击进入包无忧管理系统；
2、点击“查询快件”并进入相应的页面；
3、任意选择一个店铺，选择搜索类型：条形码，在其后输入框输入错误的运单号：524786355，点击“查询”按钮；
4、此时无加载提示，以及当并未查询到步骤3所示运单记录时，没有“未查询到记录”的提示；
5、期望结果：搜索时，有加载的提示以及有“未查询到记录”的提示。

**Comment by smileyWay** [comment]
已修复。
