### ISSUE TITLE
[BUG]  [UI]  包无忧管理系统  BUG-0005  在查询快件页面，无法通过键盘上的enter键代替页面的“查询”按钮功能

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#5]
1、点击进入包无忧管理系统；
2、点击“查询快件”栏进入相应的页面；
3、选择任意店铺，选择搜索类型（搜索类型可以任意选择）：电话号码，输入电话号码：15281099163，使用键盘上的enter键代替查询按钮，此时会直接退出查询快件页面；
4、“盘点余件”页面情况一样；
5、期望结果：可以使用键盘上的enter键代替页面的查询按钮进行查询。

**Comment by smileyWay** [comment]
暂时不修复
