### ISSUE TITLE
[BUG]  [UI]  包无忧管理系统  BUG-0006  以运单尾号查询快件时，请选择条码选择框在重置时使电话号码／条形码／取件密码输入框显示为零

### ISSUE THREAD

**Issue by 1182311224** [smileyWay/bwyWeb#6]
1、进入包无忧管理系统；
2、点击进入查询快件页面；
3、选择店铺：钢五区，选择搜索类型：条形码，“电话号码／条形码／取件密码”输入框输入钢五区店铺存在的正确运单号尾号：3534（完整运单号：377273363534）；
4、点击“查询”按钮，页面出现“请选择条码”选择框；
5、点击“请选择条码”框，选择步骤3所示的完整正确运单号，此时“电话号码／条形码／取件密码”输入框显示已被选择的正确运单号；
6、重新点击“请选择条码”选择框，选择“请选择条码”项，此时“电话号码／条形码／取件密码”输入框重置为零；
7、期望结果：操作步骤6时，“电话号码／条形码／取件密码”输入框重置为空格；

**Comment by smileyWay** [comment]
已修复。

**Comment by 1182311224** [comment]
问题已修复。
